version: "3.9"

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"

# services:
#   db:
#     image: sencha/sqlite3:latest
#     volumes:
#       - ./data/db:/root/db
#     environment:
#       - SQLITE3_DB=db.sqlite3
#   web:
#     build: .
#     command: python3.9 manage.py runserver 172.0.0.1:8000
#     volumes:
#       - .:/code
#     ports:
#       - "8000:8000"
#     depends_on:
#       - db
