# Generated by Django 3.2 on 2021-12-14 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='question_nr',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
