# Generated by Django 3.2 on 2022-01-10 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_task_image_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='image_link',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
