# Generated by Django 3.2 on 2022-01-12 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20220112_1224'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='AnswerTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('task_set', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='website.taskset')),
            ],
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.AddField(
            model_name='answerchoice',
            name='answer_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.answertypes'),
        ),
    ]
