# Generated by Django 3.2 on 2022-01-17 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20220112_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answerchoice',
            name='answer_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.task'),
        ),
        migrations.DeleteModel(
            name='AnswerTypes',
        ),
    ]
