# Generated by Django 3.2 on 2022-01-17 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20220117_1223'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answerchoice',
            old_name='answer_type',
            new_name='answer',
        ),
        migrations.AddField(
            model_name='answerchoice',
            name='image_link',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='answerchoice',
            name='text',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
