# Generated by Django 3.2 on 2022-01-17 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_auto_20220117_1224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answerchoice',
            name='image_link',
        ),
    ]
