# Generated by Django 3.2 on 2022-01-19 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_remove_answerchoice_image_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answerchoice',
            old_name='answer',
            new_name='task',
        ),
    ]
