# Generated by Django 3.2 on 2022-01-19 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_task_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='details',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
