# Generated by Django 3.2 on 2022-01-20 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sessions', '0001_initial'),
        ('website', '0011_alter_task_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_p1', models.CharField(max_length=128)),
                ('list_p2', models.CharField(max_length=128)),
                ('list_m1', models.CharField(max_length=128)),
                ('list_m2', models.CharField(max_length=128)),
                ('terms_agree', models.BooleanField()),
                ('finished', models.BooleanField()),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sessions.session')),
            ],
        ),
        migrations.CreateModel(
            name='PersonalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('nationality', models.CharField(max_length=128)),
                ('gender', models.CharField(max_length=20)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sessions.session')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionnaireSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=20)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sessions.session')),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sessions.session')),
            ],
        ),
        migrations.CreateModel(
            name='TaskSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.IntegerField()),
                ('answer', models.CharField(max_length=20)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sessions.session')),
                ('submission', models.ManyToManyField(to='website.Submission')),
            ],
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.AddField(
            model_name='questionnairesubmission',
            name='submission',
            field=models.ManyToManyField(to='website.Submission'),
        ),
        migrations.AddField(
            model_name='personaldata',
            name='submission',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='website.submission'),
        ),
        migrations.AddField(
            model_name='generaldata',
            name='submission',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='website.submission'),
        ),
    ]
