# Generated by Django 3.2 on 2022-01-21 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_auto_20220121_1123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionnairesubmission',
            name='submission',
        ),
        migrations.AddField(
            model_name='questionnairesubmission',
            name='submission',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='website.submission'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='tasksubmission',
            name='submission',
        ),
        migrations.AddField(
            model_name='tasksubmission',
            name='submission',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='website.submission'),
            preserve_default=False,
        ),
    ]
