# Generated by Django 3.2 on 2022-01-21 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_auto_20220121_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnairesubmission',
            name='questionnaire_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
