# Generated by Django 3.2 on 2022-01-21 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_questionnairesubmission_questionnaire_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionnaire',
            name='study',
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='study',
            field=models.ManyToManyField(related_name='questionnaires', to='website.Study'),
        ),
        migrations.RemoveField(
            model_name='taskset',
            name='study',
        ),
        migrations.AddField(
            model_name='taskset',
            name='study',
            field=models.ManyToManyField(related_name='tasks', to='website.Study'),
        ),
    ]
