# Generated by Django 3.2 on 2022-01-21 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_auto_20220121_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='gender',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='nationality',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
