# Generated by Django 3.2 on 2022-01-21 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_auto_20220121_1217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='text',
        ),
        migrations.AddField(
            model_name='task',
            name='item',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
