# Generated by Django 3.2 on 2022-01-22 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0019_submission_study'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionnairesubmission',
            old_name='description',
            new_name='type',
        ),
        migrations.AddField(
            model_name='tasksubmission',
            name='item',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tasksubmission',
            name='type',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
