# Generated by Django 3.2 on 2022-01-23 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0020_auto_20220122_1203'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionnairesubmission',
            old_name='questionnaire_id',
            new_name='question_id',
        ),
        migrations.AddField(
            model_name='questionnairesubmission',
            name='item',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
