# Generated by Django 3.2 on 2022-01-24 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0021_auto_20220123_1417'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='nationality',
        ),
    ]
