# Generated by Django 3.2 on 2022-02-15 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0022_remove_submission_nationality'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='framing',
            field=models.IntegerField(null=True),
        ),
    ]
