# Generated by Django 3.2 on 2022-03-30 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0025_submission_request_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='suspect_deception',
            field=models.TextField(null=True),
        ),
    ]
