# Generated by Django 3.2 on 2022-03-30 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0026_submission_suspect_deception'),
    ]

    operations = [
        migrations.AddField(
            model_name='answerchoice',
            name='correct_answer',
            field=models.BooleanField(default=False),
        ),
    ]
