# Generated by Django 3.2 on 2022-03-30 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sessions', '0001_initial'),
        ('website', '0027_answerchoice_correct_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_pre', models.CharField(max_length=20)),
                ('score_main', models.CharField(max_length=20)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sessions.session')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.submission')),
            ],
        ),
    ]
