# Generated by Django 3.2 on 2022-03-30 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0028_taskscore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskscore',
            name='score_main',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='taskscore',
            name='score_pre',
            field=models.IntegerField(default=0),
        ),
    ]
