# Generated by Django 3.2 on 2022-03-31 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0029_auto_20220330_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnairesubmission',
            name='question_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.question'),
        ),
    ]
