# Generated by Django 3.2 on 2022-04-05 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0030_alter_questionnairesubmission_question_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='suspect_deception',
            field=models.TextField(blank=True, default=''),
        ),
    ]
