# Generated by Django 3.2 on 2022-04-05 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0031_alter_submission_suspect_deception'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='suspect_deception',
            field=models.TextField(null=True),
        ),
    ]
