# Generated by Django 3.2 on 2022-04-19 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0032_alter_submission_suspect_deception'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='age',
            field=models.TextField(max_length=25, null=True),
        ),
    ]
