# Generated by Django 3.2 on 2022-04-30 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0033_alter_submission_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='text_deception',
            field=models.BooleanField(null=True),
        ),
    ]
