# Generated by Django 3.2 on 2022-04-30 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0034_submission_text_deception'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='suspect_deception',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='text_deception',
            field=models.TextField(null=True),
        ),
    ]
