# Generated by Django 3.2 on 2022-05-02 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sessions', '0001_initial'),
        ('website', '0035_auto_20220430_1048'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSpend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_nr', models.IntegerField(default=0)),
                ('start_time', models.DateTimeField()),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sessions.session')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.submission')),
            ],
        ),
    ]
