# Generated by Django 3.2 on 2022-05-02 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0036_timespend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timespend',
            name='start_time',
            field=models.FloatField(),
        ),
    ]
