# Generated by Django 3.2 on 2022-05-15 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0037_alter_timespend_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='gender',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
