# Generated by Django 3.2 on 2022-05-15 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0038_alter_submission_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='text_deception',
            field=models.TextField(blank=True, null=True),
        ),
    ]
