# Generated by Django 3.2 on 2022-06-02 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0040_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraAnswerChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, default='', max_length=200)),
                ('correct_answer', models.BooleanField(default=False)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.task')),
            ],
        ),
        migrations.CreateModel(
            name='ExtraTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('details', models.CharField(blank=True, default='', max_length=20)),
                ('item', models.CharField(blank=True, default='', max_length=200)),
                ('image_link', models.CharField(blank=True, default='', max_length=200)),
                ('task_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.taskset')),
            ],
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
