# Generated by Django 3.2 on 2022-06-02 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0041_auto_20220602_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extratask',
            name='description',
            field=models.CharField(max_length=300),
        ),
    ]
