# Generated by Django 3.2 on 2022-06-02 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0042_alter_extratask_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extratask',
            name='description',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='extratask',
            name='details',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
