# Generated by Django 3.2 on 2022-06-02 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0043_auto_20220602_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extraanswerchoice',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.extratask'),
        ),
    ]
