# Generated by Django 3.2 on 2022-06-08 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0044_alter_extraanswerchoice_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskscore',
            name='score_extra',
            field=models.IntegerField(default=0),
        ),
    ]
