# Generated by Django 3.2 on 2022-06-08 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sessions', '0001_initial'),
        ('website', '0045_taskscore_score_extra'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraTaskSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.IntegerField()),
                ('answer', models.CharField(max_length=20)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sessions.session')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.submission')),
            ],
        ),
    ]
